### ISSUE TITLE
cargo build failing

### ISSUE THREAD

**Issue by goosetherumfoodle** [whisperfish/presage#102]
Adding this dependency in cargo.toml:
```
...

[dependencies]
presage = { git = "https://github.com/whisperfish/presage" }

...
```

and then doing `cargo build`, I get the following error:
```
...

Caused by:
Unable to update https://github.com/whisperfish/libsignal-service-rs?rev=bfc293000e058924771c0651c16bb19fb778c4ef

Caused by:
revspec 'bfc293000e058924771c0651c16bb19fb778c4ef' not found; class=Reference (4); code=NotFound (-3)
```

**Comment by gferon** [comment]
Oh yeah, I should make this clear in the README.

Because of some issues with the maintenance of `curve25519_dalek`, Signal decided to fork the crate.

To workaround this compilation issue, you should copy the `[patch]` section of the `Cargo.toml` of `presage` in your own project.

Feel free to contact me on Matrix (I'm `gferon:matrix.org`) if you have any questions, it might be faster over there.
