### ISSUE TITLE
Add message storage

### ISSUE THREAD

**Issue by gferon** [whisperfish/presage#44]
Move the message storage from https://github.com/boxdot/gurk-rs/ to presage, which should make it more useful. This will also make implementing encryption easier, since it'll be in a single place. Pinging @boxdot to fill in the details.

**Comment by gferon** [comment]
As discussed with @boxdot it could be interesting to have this as some sort of plug-in for the crate, as it's a valid use-case to _not_ have this.

**Comment by boxdot** [comment]
I think it is very beneficial to be able to use this crate as a lean library for writing tiny notifications bots or similar. In such scenarios, there is actually no need to store anything. And even storing something might be harmful, since the bots might run anywhere.

On the other hand, it totally makes sense to add a storage to presage, since the data is going through presage anyway.

I would propose to design a Storage trait and provide two impls: one based on sled and one ephemeral. The ephemeral storage would store in memory only. With the trait it is also simple to finally implement encryption of the storage.
